### ISSUE TITLE
Compiling web components into their own files.

### ISSUE THREAD

**Issue by jonathanblancor** [sinedied/svelte-web-components-template#2]
Hello,

This projects puts all web components into one file when building. Is there a way to compile each component into their own files? Like having one `.js` per component.

I would like to be able to do this because I want to pick and choose which components to use on another project without having to load the whole file. For example, if I have 3 components, I want be able to just select 2 of those and use them on another project, instead of using one file with all 3 components in it.

**Comment by sinedied** [comment]
You'll be pleased to see that I just add docs and config to do just that, see this section: https://github.com/sinedied/svelte-web-components-template#building-each-component-into-its-own-module

**Comment by jonathanblancor** [comment]
Thank you for the answer. I was able to generate separate files using other examples I found online. My next step now is trying to do the same thing in Sveltekit. 

If you have any idea how let me know! Thanks!

**Comment by choiadam** [comment]
Hi, I have just cloned this template and followed your steps to build it into separate modules. `npm run build` works great, however, I now have a problem where the demo part doesn't work for local development. When running `npm run dev` it has stopped showing the component on `localhost:5000`. 

Are you able to replicate this issue? And do you have any ideas for how to get this to work?

**Comment by sinedied** [comment]
You just need to update the imports in the demo app, I've updated the readme with instructions on how to do that.
