### ISSUE TITLE
Component refresh

### ISSUE THREAD

**Issue by paolodina** [sinedied/svelte-web-components-template#4]
Is component refresh supposed to update the page on save?

In my case I've been able to make it work adding [this](https://github.com/nuclia/demos/blob/main/custom-component-dev/index.html#L12) [js](https://github.com/nuclia/demos/blob/main/custom-component-dev/index.html#L13) to `index.html` ([blog post](https://nuclia.com/developers/how-to-run-svelte-custom-elements-in-dev-mode/)).

Btw, nice template!

**Comment by sinedied** [comment]
You're right, seems this is a regression since the Vite migration. HMR doesn't to play well with web components (as seen in the blog post you linked 😉 ), so I enabled proper reload instead.
