### ISSUE TITLE
Cannot import non web components into a wc.svelte file

### ISSUE THREAD

**Issue by malindsay** [sinedied/svelte-web-components-template#6]
As soon as I add an import of a 3rd party package, the wc fails to load because it is taking all imported components as a WC. 

<img width="533" alt="image" src="https://user-images.githubusercontent.com/95309541/214887998-8427d9cc-2fda-41ef-b47f-2a047b59bf63.png">

**Comment by malindsay** [comment]
Figured it out... I just needed to reverse the order of these:
    svelte({
      exclude: /\.wc\.svelte$/ as any
    }),
    svelte({
      include: /\.wc\.svelte$/ as any,
      compilerOptions: {
        customElement: true
      }
    })

**Comment by sinedied** [comment]
Thanks for reporting the issue, I never had the case but I inverted the plugins processing as you said.
